CREATE TABLE property (
  property_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   title VARCHAR(255),
   description VARCHAR(255),
   address VARCHAR(255),
   price FLOAT NOT NULL,
   available BOOLEAN NOT NULL,
   images TEXT[],
   creation_date TIMESTAMP,
   owner_id BIGINT,
   CONSTRAINT pk_property PRIMARY KEY (property_id)
);

ALTER TABLE property ADD CONSTRAINT FK_PROPERTY_ON_OWNER FOREIGN KEY (owner_id) REFERENCES tab_user (user_id);